/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LSP4DigitalAssetMetadata } from "./LSP4DigitalAssetMetadata";
export type { LSP4DigitalAssetMetadataCore } from "./LSP4DigitalAssetMetadataCore";
