/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as custom from "./custom";
export * as interfaces from "./interfaces";
export { ERC725Y__factory } from "./ERC725Y__factory";
export { ERC725YCore__factory } from "./ERC725YCore__factory";
