/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface TokenReceiverWithLSP1Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "fund"
      | "getBalance"
      | "isValidSignature"
      | "mint"
      | "supportsInterface"
      | "universalReceiver"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "UniversalReceiver"): EventFragment;

  encodeFunctionData(functionFragment: "fund", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSignature",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "universalReceiver",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isValidSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "universalReceiver",
    data: BytesLike
  ): Result;
}

export namespace UniversalReceiverEvent {
  export type InputTuple = [
    from: AddressLike,
    value: BigNumberish,
    typeId: BytesLike,
    receivedData: BytesLike,
    returnedValue: BytesLike
  ];
  export type OutputTuple = [
    from: string,
    value: bigint,
    typeId: string,
    receivedData: string,
    returnedValue: string
  ];
  export interface OutputObject {
    from: string;
    value: bigint;
    typeId: string;
    receivedData: string;
    returnedValue: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TokenReceiverWithLSP1 extends BaseContract {
  connect(runner?: ContractRunner | null): TokenReceiverWithLSP1;
  waitForDeployment(): Promise<this>;

  interface: TokenReceiverWithLSP1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  fund: TypedContractMethod<[], [void], "payable">;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  isValidSignature: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [string],
    "view"
  >;

  mint: TypedContractMethod<
    [_bpunx: AddressLike, _amount: BigNumberish],
    [void],
    "payable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  universalReceiver: TypedContractMethod<
    [typeId: BytesLike, data: BytesLike],
    [string],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "fund"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isValidSignature"
  ): TypedContractMethod<[arg0: BytesLike, arg1: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [_bpunx: AddressLike, _amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "universalReceiver"
  ): TypedContractMethod<
    [typeId: BytesLike, data: BytesLike],
    [string],
    "payable"
  >;

  getEvent(
    key: "UniversalReceiver"
  ): TypedContractEvent<
    UniversalReceiverEvent.InputTuple,
    UniversalReceiverEvent.OutputTuple,
    UniversalReceiverEvent.OutputObject
  >;

  filters: {
    "UniversalReceiver(address,uint256,bytes32,bytes,bytes)": TypedContractEvent<
      UniversalReceiverEvent.InputTuple,
      UniversalReceiverEvent.OutputTuple,
      UniversalReceiverEvent.OutputObject
    >;
    UniversalReceiver: TypedContractEvent<
      UniversalReceiverEvent.InputTuple,
      UniversalReceiverEvent.OutputTuple,
      UniversalReceiverEvent.OutputObject
    >;
  };
}
