/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as extensions from "./extensions";
export { ILSP8IdentifiableDigitalAsset__factory } from "./ILSP8IdentifiableDigitalAsset__factory";
export { LSP8IdentifiableDigitalAsset__factory } from "./LSP8IdentifiableDigitalAsset__factory";
export { LSP8IdentifiableDigitalAssetCore__factory } from "./LSP8IdentifiableDigitalAssetCore__factory";
