/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  BPunX,
  BPunXInterface,
} from "../../../../contracts/mocks/TokenReceiverLSP1.sol/BPunX";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class BPunX__factory {
  static readonly abi = _abi;
  static createInterface(): BPunXInterface {
    return new Interface(_abi) as BPunXInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): BPunX {
    return new Contract(address, _abi, runner) as unknown as BPunX;
  }
}
