/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as custom from "./custom";
export type { custom };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { ERC725Y } from "./ERC725Y";
export type { ERC725YCore } from "./ERC725YCore";
